insert into secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
values
(83, 2, 7, 'CANCELAR', 8, 8, SYSDATE(), 1);

insert into secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
values
(82, 2, 10, 'CANCELAR', 8, 8, SYSDATE(), 1);
