CREATE TABLE secopre.AUTHORIZATION (
  ID bigint(20) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  SUPER_USER_ROLE bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  KEY FK_AUTH_ROLE (SUPER_USER_ROLE),
  CONSTRAINT FK_AUTH_ROLE FOREIGN KEY (SUPER_USER_ROLE) REFERENCES secopre.ROLE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.STAGE (
  ID bigint(20) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.STAGE_CONFIG (
  ID bigint(20) NOT NULL,
  STAGE_ID bigint(20) NOT NULL,
  PATH_ID bigint(20) NOT NULL,
  IS_CAPTURE bit(1) NOT NULL,
  IS_AUTHORIZATION bit(1) NOT NULL,
  CAPTURE_FORM varchar(255) DEFAULT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  KEY FK_STG_CFG_STG (STAGE_ID),
  KEY FK_STG_CFG_PATH (PATH_ID),
  CONSTRAINT FK_STG_CFG_PATH FOREIGN KEY (PATH_ID) REFERENCES secopre.PATH (ID),
  CONSTRAINT FK_STG_CFG_STG FOREIGN KEY (STAGE_ID) REFERENCES secopre.STAGE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.STAGE_CONFIG_ROLE (
  STAGE_CONFIG_ID bigint(20) NOT NULL,
  ROLE_ID bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  UNIQUE KEY IDX_STG_CFG_ROLE (ROLE_ID,STAGE_CONFIG_ID),
  KEY STG_CFG_RL_STGCFG (STAGE_CONFIG_ID),
  CONSTRAINT STG_CFG_RL_ROLE FOREIGN KEY (ROLE_ID) REFERENCES secopre.ROLE (ID),
  CONSTRAINT STG_CFG_RL_STGCFG FOREIGN KEY (STAGE_CONFIG_ID) REFERENCES secopre.STAGE_CONFIG (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.AUTHORIZATION_CONFIG (
  ID bigint(20) NOT NULL,
  AUTHORIZATION_ID bigint(20) NOT NULL,
  STAGE_CONFIG_ID bigint(20) NOT NULL,
  EMPLOYMENT_ID bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  KEY FK_AUTH_CFG_STG_CFG (STAGE_CONFIG_ID),
  CONSTRAINT FK_AUTH_CFG_STG_CFG FOREIGN KEY (STAGE_CONFIG_ID) REFERENCES secopre.STAGE_CONFIG (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.CHAT_CONVERSATION (
  CONVERSATION_ID bigint(20) NOT NULL,
  USER_ID bigint(20) NOT NULL,
  CREATION_DATE date DEFAULT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  UNIQUE KEY UDX_CHAT_CONV_USER (CONVERSATION_ID,USER_ID),
  KEY fk_chat_conv_user (USER_ID),
  CONSTRAINT fk_chat_conv_user FOREIGN KEY (USER_ID) REFERENCES secopre.USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.CHAT_MESSAGE (
  MESSAGE_ID bigint(20) NOT NULL AUTO_INCREMENT,
  CONVERSATION_ID bigint(20) NOT NULL,
  USER_FROM bigint(20) NOT NULL,
  USER_TO bigint(20) NOT NULL,
  MESSAGE varchar(1000) NOT NULL,
  ESTATUS int(1) NOT NULL DEFAULT 0,
  CREATION_DATE datetime DEFAULT NULL,
  LAST_UPDATE datetime DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (MESSAGE_ID),
  KEY FK_C_MSG_CONV (CONVERSATION_ID),
  KEY FK_C_MSG_USR_FROM (USER_FROM),
  KEY FK_C_MSG_USR_TO (USER_TO),
  CONSTRAINT FK_C_MSG_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES secopre.CHAT_CONVERSATION (CONVERSATION_ID),
  CONSTRAINT FK_C_MSG_USR_FROM FOREIGN KEY (USER_FROM) REFERENCES secopre.USER (ID),
  CONSTRAINT FK_C_MSG_USR_TO FOREIGN KEY (USER_TO) REFERENCES secopre.USER (ID)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8;

CREATE TABLE secopre.EMPLOYMENT (
  EMPLOYMENT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(255) NOT NULL,
  CREATION_DATE datetime DEFAULT NULL,
  LAST_UPDATE datetime DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (EMPLOYMENT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REL_USER_CONNECTION (
  USER_ID bigint(20) NOT NULL,
  SOCKET_ID varchar(255) DEFAULT NULL,
  CREATION_DATE datetime DEFAULT NULL,
  LAST_UPDATE datetime DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (USER_ID),
  CONSTRAINT FK_REL_UC_USR FOREIGN KEY (USER_ID) REFERENCES secopre.USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REL_USER_EMPLOYMENT (
  USER_ID bigint(20) NOT NULL,
  EMPLOYMENT_ID bigint(20) NOT NULL,
  CREATION_DATE datetime DEFAULT NULL,
  LAST_UPDATE datetime DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  KEY FK_UE_USR (USER_ID),
  KEY FK_UE_EMP (EMPLOYMENT_ID),
  CONSTRAINT FK_UE_EMP FOREIGN KEY (EMPLOYMENT_ID) REFERENCES secopre.EMPLOYMENT (EMPLOYMENT_ID),
  CONSTRAINT FK_UE_USR FOREIGN KEY (USER_ID) REFERENCES secopre.USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REQUEST (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(255) DEFAULT NULL,
  PARENT_LAST_NAME varchar(255) DEFAULT NULL,
  MOTHER_LAST_NAME varchar(255) DEFAULT NULL,
  LAST_UPDATE datetime DEFAULT CURRENT_TIMESTAMP,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.WORKFLOW (
  ID bigint(20) NOT NULL,
  DESCRIPTION varchar(255) NOT NULL,
  FIRST_STAGE_CFG bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  KEY FK_WF_CFG_STG (FIRST_STAGE_CFG),
  CONSTRAINT FK_WF_CFG_STG FOREIGN KEY (FIRST_STAGE_CFG) REFERENCES secopre.STAGE_CONFIG (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.WORKFLOW_CONFIG_CODE (
  ID bigint(20) NOT NULL,
  CODE varchar(255) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  UNIQUE KEY IDX_CODE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.STATUS (
  ID bigint(20) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.WORKFLOW_CONFIG (
  ID bigint(20) NOT NULL,
  WORKFLOW_ID bigint(20) NOT NULL,
  STAGE_CONFIG_ID bigint(20) NOT NULL,
  WF_CFG_CODE varchar(255) NOT NULL,
  NEXT_STAGE_CONFIG bigint(20) NOT NULL,
  STATUS_ID bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (ID),
  KEY FK_WF_CFG_STG_CFG (STAGE_CONFIG_ID),
  KEY FK_WF_CFG_NXT_STG (NEXT_STAGE_CONFIG),
  KEY FK_WF_CFG_CODE (WF_CFG_CODE),
  KEY FK_WF_CFG_STATUS (STATUS_ID),
  KEY FK_WF_CFG_WF (WORKFLOW_ID),
  CONSTRAINT FK_WF_CFG_CODE FOREIGN KEY (WF_CFG_CODE) REFERENCES secopre.WORKFLOW_CONFIG_CODE (CODE),
  CONSTRAINT FK_WF_CFG_NXT_STG FOREIGN KEY (NEXT_STAGE_CONFIG) REFERENCES secopre.STAGE_CONFIG (ID),
  CONSTRAINT FK_WF_CFG_STATUS FOREIGN KEY (STATUS_ID) REFERENCES secopre.STATUS (ID),
  CONSTRAINT FK_WF_CFG_STG_CFG FOREIGN KEY (STAGE_CONFIG_ID) REFERENCES secopre.STAGE_CONFIG (ID),
  CONSTRAINT FK_WF_CFG_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES secopre.WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REQUEST_CONFIG (
  REQUEST_ID bigint(20) NOT NULL,
  FORMALITY_ID bigint(20) NOT NULL,
  WORKFLOW_ID bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  AUTHORIZATION_ID bigint(20) NOT NULL,
  KEY REQ_CFG_WF (WORKFLOW_ID),
  CONSTRAINT REQ_CFG_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES secopre.WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REQUEST_DETAIL (
  REQUEST_ID bigint(20) NOT NULL,
  MOVEMENT_NAME varchar(100) DEFAULT NULL,
  MOVEMENT_PRICE decimal(10,0) DEFAULT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1,
  PRIMARY KEY (REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE secopre.REQUEST_HISTORY (
  REQUEST_ID bigint(20) NOT NULL,
  CONSECUTIVE bigint(20) NOT NULL,
  WORKFLOW_CONFIG_ID bigint(20) NOT NULL,
  USER_ID bigint(20) NOT NULL,
  LAST_UPDATE date DEFAULT NULL,
  ACTIVE bit(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
