-- status
INSERT INTO secopre.STATUS
(ID, DESCRIPTION, LAST_UPDATE, ACTIVE)
VALUES
(10, 'Operar Movimiento', SYSDATE(), 1);

-- stage
-- etapa de operacion
INSERT INTO secopre.STAGE
(ID, DESCRIPTION, LAST_UPDATE, ACTIVE)
VALUES
(7, 'Operación de Movimiento', sysdate(), 1);

-- stage config
-- etapa de captura completa de gastos
INSERT INTO secopre.STAGE_CONFIG
(ID, STAGE_ID, PATH_ID, IS_CAPTURE, IS_AUTHORIZATION, CAPTURE_FORM, LAST_UPDATE, ACTIVE, IS_END_WORKFLOW)
VALUES
(10, 2, 8, 1, 0, 'expense', sysdate(), 1, 0);

--etapa de operacion de movimiento

INSERT INTO secopre.STAGE_CONFIG
(ID, STAGE_ID, PATH_ID, IS_CAPTURE, IS_AUTHORIZATION, CAPTURE_FORM, LAST_UPDATE, ACTIVE, IS_END_WORKFLOW)
VALUES
(11, 7, 9, 0, 1, '', sysdate(), 1, 0);

-- workflow config

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(13,2, 1, 'SOLPEND', 1, 1, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(14, 2, 1, 'SOLCOMP', 10, 2, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(15, 2, 10, 'SOLPEND', 10, 2, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(16, 2, 10, 'SOLCOMP', 11, 10, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(17,2,  11, 'CONTINUAR', 7, 7, SYSDATE(), 1);

-- workflow

INSERT INTO secopre.WORKFLOW
(ID, DESCRIPTION, FIRST_STAGE_CFG, LAST_UPDATE, ACTIVE)
VALUES
(2, 'Flujo de Gastos', 1, SYSDATE(), 1);

-- tramite
INSERT INTO secopre.FORMALITY
(ID, DESCRIPTION, WORKFLOW_ID, LAST_UPDATE, ACTIVE, AUTHORIZATION_ID, CODE)
VALUES
(2, 'Trámite de Gastos', 2, sysdate(), 1, 2, 'expense');

-- rol universal, este no deberia estar asignado a nadie, cuando una etapa lo tenga asignado, significa que cualquier usuario tiene acceso
INSERT INTO secopre.ROLE
(ID, ACTIVE, ROLENAME)
VALUES
(-1, 1, 'ROLE_UNIVERSAL');

-- stage config role
INSERT INTO secopre.STAGE_CONFIG_ROLE
(STAGE_CONFIG_ID, ROLE_ID, LAST_UPDATE, ACTIVE)
VALUES
(10, 2, sysdate(), 1);

INSERT INTO secopre.STAGE_CONFIG_ROLE
(STAGE_CONFIG_ID, ROLE_ID, LAST_UPDATE, ACTIVE)
VALUES
(11, -1, sysdate(), 1);

COMMIT;

/* query para obtener toda la configuracion del flujo */

SELECT W.DESCRIPTION,
	   SC1.ID,
	   S1.DESCRIPTION,
	   WC.WF_CFG_CODE,
	   SC2.ID,
	   S1.DESCRIPTION,
	   S.DESCRIPTION
  FROM secopre.WORKFLOW_CONFIG WC,
  	   secopre.WORKFLOW W,
  	   secopre.STAGE_CONFIG SC1,
  	   secopre.STAGE S1,
  	   secopre.STAGE_CONFIG SC2,
  	   secopre.STAGE S2,
  	   secopre.STATUS S
  	   WHERE W.ID = 2
   AND WC.WORKFLOW_ID = W.ID
   AND WC.STAGE_CONFIG_ID = SC1.ID
   AND SC1.STAGE_ID = S1.ID
   AND WC.NEXT_STAGE_CONFIG = SC2.ID
   AND SC2.STAGE_ID = S2.ID
   AND WC.STATUS_ID = S.ID
   
 /* ALTER PARA BANDERAS DE OPERACION EN ETAPAS */  
   alter table secopre.STAGE_CONFIG ADD(
   		IS_CANCELED BIT(1) NOT NULL DEFAULT FALSE,
   		IS_OPERATED BIT(1) NOT NULL DEFAULT FALSE
   );
   
 /* WORKFLOW CONFIG DE MOVIMIENTOS SIN CARGA DE ARCHIVO */
 
 INSERT INTO secopre.workflow_config (ID,WORKFLOW_ID,STAGE_CONFIG_ID,WF_CFG_CODE,NEXT_STAGE_CONFIG,STATUS_ID,LAST_UPDATE,ACTIVE) VALUES 
(1,1,1,'SOLPEND',1,1,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(2,1,1,'SOLCOMP',2,2,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(3,1,2,'SOLPEND',2,2,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(4,1,2,'SOLCOMP',3,3,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(5,1,3,'SIGFIRMA',4,4,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(6,1,3,'REGRESAR',2,2,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(7,1,3,'CONTINUAR',7,7,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(8,1,3,'CANCELAR',8,8,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(9,1,4,'SIGFIRMA',5,5,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(10,1,4,'REGRESAR',3,3,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
;
INSERT INTO secopre.workflow_config (ID,WORKFLOW_ID,STAGE_CONFIG_ID,WF_CFG_CODE,NEXT_STAGE_CONFIG,STATUS_ID,LAST_UPDATE,ACTIVE) VALUES 
(11,1,4,'CONTINUAR',7,7,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(12,1,4,'CANCELAR',7,8,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(13,1,5,'SIGFIRMA',6,6,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(14,1,5,'REGRESAR',4,4,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(15,1,5,'CONTINUAR',7,7,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(16,1,5,'CANCELAR',8,8,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(17,1,6,'REGRESAR',5,5,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(18,1,6,'CONTINUAR',7,7,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
,(19,1,6,'CANCELAR',8,8,STR_TO_DATE('2015-09-07','%Y-%m-%d'),true)
;