-- status
INSERT INTO secopre.STATUS
(ID, DESCRIPTION, LAST_UPDATE, ACTIVE)
VALUES
(10, 'Operar Movimiento', SYSDATE(), 1);

-- stage
-- etapa de operacion
INSERT INTO secopre.STAGE
(ID, DESCRIPTION, LAST_UPDATE, ACTIVE)
VALUES
(7, 'Operación de Movimiento', sysdate(), 1);

-- stage config
-- etapa de captura completa de gastos
INSERT INTO secopre.STAGE_CONFIG
(ID, STAGE_ID, PATH_ID, IS_CAPTURE, IS_AUTHORIZATION, CAPTURE_FORM, LAST_UPDATE, ACTIVE, IS_END_WORKFLOW)
VALUES
(10, 2, 8, 1, 0, 'expense', sysdate(), 1, 0);

--etapa de operacion de movimiento

INSERT INTO secopre.STAGE_CONFIG
(ID, STAGE_ID, PATH_ID, IS_CAPTURE, IS_AUTHORIZATION, CAPTURE_FORM, LAST_UPDATE, ACTIVE, IS_END_WORKFLOW)
VALUES
(11, 7, 9, 0, 1, '', sysdate(), 1, 0);

-- workflow config

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(13,2, 1, 'SOLPEND', 1, 1, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(14, 2, 1, 'SOLCOMP', 10, 2, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(15, 2, 10, 'SOLPEND', 10, 2, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(16, 2, 10, 'SOLCOMP', 11, 10, SYSDATE(), 1);

INSERT INTO secopre.WORKFLOW_CONFIG
(ID, WORKFLOW_ID, STAGE_CONFIG_ID, WF_CFG_CODE, NEXT_STAGE_CONFIG, STATUS_ID, LAST_UPDATE, ACTIVE)
VALUES
(17,2,  11, 'CONTINUAR', 7, 7, SYSDATE(), 1);

-- workflow

INSERT INTO secopre.WORKFLOW
(ID, DESCRIPTION, FIRST_STAGE_CFG, LAST_UPDATE, ACTIVE)
VALUES
(2, 'Flujo de Gastos', 1, SYSDATE(), 1);

-- tramite
INSERT INTO secopre.FORMALITY
(ID, DESCRIPTION, WORKFLOW_ID, LAST_UPDATE, ACTIVE, AUTHORIZATION_ID, CODE)
VALUES
(2, 'Trámite de Gastos', 2, sysdate(), 1, 2, 'expense');

-- rol universal, este no deberia estar asignado a nadie, cuando una etapa lo tenga asignado, significa que cualquier usuario tiene acceso
INSERT INTO secopre.ROLE
(ID, ACTIVE, ROLENAME)
VALUES
(-1, 1, 'ROLE_UNIVERSAL');

-- stage config role
INSERT INTO secopre.STAGE_CONFIG_ROLE
(STAGE_CONFIG_ID, ROLE_ID, LAST_UPDATE, ACTIVE)
VALUES
(10, 2, sysdate(), 1);

INSERT INTO secopre.STAGE_CONFIG_ROLE
(STAGE_CONFIG_ID, ROLE_ID, LAST_UPDATE, ACTIVE)
VALUES
(11, -1, sysdate(), 1);

COMMIT;