SET GLOBAL event_scheduler = ON;

CREATE EVENT CLEAN_SOCKET_UPDATE
  ON SCHEDULE
    EVERY 1 DAY
    STARTS '2016-07-12 00:00:00' ON COMPLETION PRESERVE ENABLE 
  DO
    DELETE FROM secopre.REL_USER_CONNECTION WHERE USER_ID >= 1;